language: php

php:
  - 7.1
  - 7.2
  - 7.3
    
env:
  - SWOOLE_VERSION=swoole-4.0.4
  - SWOOLE_VERSION=swoole-4.1.2
  - SWOOLE_VERSION=swoole-4.2.13
  - SWOOLE_VERSION=swoole-4.3.6
  - SWOOLE_VERSION=swoole-4.4.8
  - SWOOLE_VERSION=swoole

jobs:
  include:
  - php: 7.4
    env: SWOOLE_VERSION=swoole-4.4.8
  - php: 7.4
    env: SWOOLE_VERSION=swoole

before_install:
  - phpenv config-rm xdebug.ini
  - pecl channel-update pecl.php.net
  - yes | pecl install -f $SWOOLE_VERSION
  - php --ri swoole

install:
  - composer install -n

script:
  - vendor/bin/phpunit
